include:
  - board: seeeduino_xiao_ble
    shield: lism_left
    snippet: non-trackball-peripheral
    artifact-name: lism_left

  - board: seeeduino_xiao_ble
    shield: lism_right
    snippet: studio-rpc-usb-uart trackball-central
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: lism_right
