# This file generates the GitHub Actions matrix.
---
include:
  - board: seeeduino_xiao_ble
    shield: lism_left
    artifact-name: lism_left

  - board: seeeduino_xiao_ble
    shield: lism_right
    artifact-name: lism_right

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble-zmk
